### ISSUE TITLE
ReferenceError: config is not defined

### ISSUE THREAD

**Issue by dzogrim** [Behemouth/WeedProxite#1]
Hello, I tried to install WeedProxite and I always get this error when I try to access it:

``` javascript
ReferenceError: config is not defined
    at Middleware.use.after (/usr/local/lib/node_modules/WeedProxite/lib/Site.js:294:55)
    at Middleware._after (/usr/local/lib/node_modules/WeedProxite/lib/Middleware.js:222:25)
    at runMiddleware (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:373:25)
    at /usr/local/lib/node_modules/WeedProxite/lib/Server.js:326:18
    at Middleware.after (/usr/local/lib/node_modules/WeedProxite/lib/Middleware.js:163:14)
    at Middleware._after (/usr/local/lib/node_modules/WeedProxite/lib/Middleware.js:222:25)
    at runMiddleware (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:373:25)
    at /usr/local/lib/node_modules/WeedProxite/lib/Server.js:326:18
    at Site.Server._prepareProxyResponse (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:329:14)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:288:24)
```

Did I miss something?
I followed installation instructions twice… different random websites: same error.

Thanks

**Comment by Behemouth** [comment]
Thanks, this edge bug now was fixed.
